name: Docs
on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  notebooks:
    name: "Build the notebooks for the docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pandoc
        run: |
          sudo apt-get install pandoc

      - name: Install and Set Up Poetry
        run: |
          python -m pip install --upgrade poetry
          poetry config virtualenvs.in-project true
          poetry run python -m pip install --upgrade pip
  
      - name: Install Dependencies
        run: |
          poetry install --extras dev_docs

      - name: Execute the notebooks
        run: |
          export TF_CPP_MIN_LOG_LEVEL=3
          find docs/source/notebooks -type f -print0 | xargs -0 -n 1 -P 8 poetry run jupytext --set-formats md,ipynb --execute
      
      - name: Build the docs
        run: |
          poetry run sphinx-build -b html docs/source docs/_build

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: docs-deploy
          FOLDER: docs/_build
          CLEAN: true
          TARGET_FOLDER: ${{ github.ref }}
          SINGLE_COMMIT: true
          PRESERVE: true
      
      - name: Print docs link
        run: |
          echo "Docs available at https://www.adriangb.com/scikeras/${{ github.ref }}"
